/* AUTO-GENERATED by update.py from portfolio.json - do not edit by hand. */
window.DASH = {
  "meta": {
    "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
    "strategy": "Conviction discipline: NO C- or D-tier positions are held unless they are needed as hedges. Non-hedge holdings must earn their A/B conviction or the money sits in cash. CUT in v5: IGV (D, software timing), ARKQ (C, robotics timing), XBI (C, biotech w/o catalyst), KWEB (C, unfundable China risk). KEPT B-tier with catalysts: XLY, EZU, IWM, IWDL (value = anti-growth factor hedge). Freed capital boosted A-tier growth (TQQQ 9k, SOXL 7k, DRAM 5k) and the strongest hedges (ZROZ 6k, QFLR 3k); the rest is dry-powder parked in SGOV (0-3 month T-bills) - idle cash is never left as cash. V5.1: leveraged-fund stop-losses are INDEX-REFERENCED (checked on the 1x underlying - TQQQ->QQQ -8%, SOXL->SOXX -9%, IWDL->IWD -10%) so a violent leveraged day or decay drift cannot whipsaw the stop; the wrapper-level stop_loss_pct is only a wide backstop. Take-profits auto-checked on the wrapper. JEPQ is an income sleeve, NOT a hedge-funding engine - hedge drag is priced insurance (T6), not financed by JEPQ. Stop losses / take profits auto-checked by update.py.",
    "currency": "USD",
    "start_value": 100000,
    "start_date": "2026-08-10",
    "rebalanced": "2026-08-10",
    "rebalance_reason": "v5 - Conviction-First mandate: drop all non-hedge C/D positions, hold cash instead. Cut IGV/ARKQ/XBI/KWEB (16k). Boosted TQQQ+2k, SOXL+2k, DRAM+1k, ZROZ+1k, QFLR+1k. Dry-powder cash (13%) is auto-parked in SGOV by update.py.",
    "limits": {
      "basis": "Effective exposure = market value x ETF leverage. Sector caps are CHECKED ON EFFECTIVE (leveraged) exposure. Caps were expanded in v5 to accommodate the 3x/2x sleeve sizing.",
      "cash_policy": "Idle cash is never left as cash - update.py auto-parks it in SGOV (0-3 month T-bills) on every run.",
      "re_entry": {
        "mode": "index_reclaim",
        "confirm_bars": 2,
        "max_pause_days": 60,
        "note": "Research-integrity protocol (v5.2): a stop is a VOL-HALT, not a death. The linked theory is marked PAUSED (only if no open position still tests it), proceeds park in SGOV. If the 1x underlying closes back above its stop level for 2 consecutive sessions the theory is RE-AFFIRMED and the position is re-entered with the recovered capital; if no reclaim within 60 days the theory is formally ABANDONED (falsified) and capital stays reallocated. Prevents the silent-SGOV-trap from quietly converting the book into a T-bill portfolio and corrupting multi-month theory tests."
      },
      "rebalance": {
        "tolerance_pct": 5.0,
        "targets": {
          "Tech / AI Growth": 60.0,
          "Nuclear / Power": 11.0,
          "Broadening / Value": 8.0,
          "Contrarian Fear": 4.5,
          "Hedge Stack": 35.0,
          "Premium Financing": 2.5,
          "Short-Term Bonds": 13.0
        },
        "note": "Passive drift threshold (v5.3): if a sector's EFFECTIVE exposure strays more than +/-5pp from its target, update.py logs a rebalance_recommended event and flags dashboard.js. It NEVER trades - it only asks the conviction layer to review the risk-budget mismatch, so path-dependent re-entry sizing cannot silently compound into a hidden risk-budget error."
      },
      "position_exposure": {
        "TQQQ": {
          "sector": "Tech / AI Growth",
          "leverage": 3.0
        },
        "SOXL": {
          "sector": "Tech / AI Growth",
          "leverage": 3.0
        },
        "SMH": {
          "sector": "Tech / AI Growth",
          "leverage": 1.0
        },
        "DRAM": {
          "sector": "Tech / AI Growth",
          "leverage": 1.0
        },
        "PLTR": {
          "sector": "Tech / AI Growth",
          "leverage": 1.0
        },
        "NLR": {
          "sector": "Nuclear / Power",
          "leverage": 1.0
        },
        "NUKZ": {
          "sector": "Nuclear / Power",
          "leverage": 1.0
        },
        "IWM": {
          "sector": "Broadening / Value",
          "leverage": 1.0
        },
        "IWDL": {
          "sector": "Broadening / Value",
          "leverage": 2.0
        },
        "XLY": {
          "sector": "Contrarian Fear",
          "leverage": 1.0
        },
        "EZU": {
          "sector": "Contrarian Fear",
          "leverage": 1.0
        },
        "ZROZ": {
          "sector": "Hedge Stack",
          "leverage": 1.0
        },
        "FXY": {
          "sector": "Hedge Stack",
          "leverage": 1.0
        },
        "VIXM": {
          "sector": "Hedge Stack",
          "leverage": 1.0
        },
        "QFLR": {
          "sector": "Hedge Stack",
          "leverage": 1.0
        },
        "GLD": {
          "sector": "Hedge Stack",
          "leverage": 1.0
        },
        "GDX": {
          "sector": "Hedge Stack",
          "leverage": 1.0
        },
        "BTAL": {
          "sector": "Hedge Stack",
          "leverage": 1.0
        },
        "DBMF": {
          "sector": "Hedge Stack",
          "leverage": 1.0
        },
        "JEPQ": {
          "sector": "Premium Financing",
          "leverage": 1.0
        },
        "SGOV": {
          "sector": "Short-Term Bonds",
          "leverage": 1.0
        }
      },
      "sector_limits": [
        {
          "sector": "Tech / AI Growth",
          "max_pct": 70,
          "note": "v5-expanded for 3x TQQQ/SOXL"
        },
        {
          "sector": "Nuclear / Power",
          "max_pct": 16
        },
        {
          "sector": "Broadening / Value",
          "max_pct": 16
        },
        {
          "sector": "Contrarian Fear",
          "max_pct": 12
        },
        {
          "sector": "Hedge Stack",
          "max_pct": 45
        },
        {
          "sector": "Premium Financing",
          "max_pct": 6
        },
        {
          "sector": "Short-Term Bonds",
          "max_pct": 20
        }
      ]
    },
    "created_by": "opencode agent (simulated managed portfolio)",
    "disclaimer": "Simulated portfolio for tracking/learning. Not financial advice.",
    "rebalance_flags": {}
  },
  "asof": "2026-08-11",
  "summary": {
    "total_value": 100313.66,
    "cash": 25.0,
    "invested_value": 100288.66,
    "day_change": 0.0,
    "total_return_pct": 0.31,
    "realized_pnl": 0.0,
    "start_value": 100000,
    "max_drawdown_pct": 0.0,
    "sharpe_annualized": null,
    "cagr_annualized": 77.17
  },
  "positions": [
    {
      "ticker": "SGOV",
      "name": "iShares 0-3 Month Treasury Bond ETF",
      "sleeve": "Short-Term Bonds (SGOV)",
      "buy_date": "2026-08-11",
      "buy_price": 100.505,
      "shares": 129.098055,
      "cost": 12975.0,
      "current_price": 100.51,
      "current_value": 12975.65,
      "pnl_pct": 0.0,
      "take_profit_pct": 0.0,
      "stop_loss_pct": -0.1,
      "status": "open",
      "exit": null,
      "sector": "Short-Term Bonds",
      "leverage": 1.0,
      "effective_value": 12975.65,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": []
    },
    {
      "ticker": "TQQQ",
      "name": "ProShares UltraPro QQQ (3x Nasdaq-100)",
      "sleeve": "Tech/AI Growth",
      "buy_date": "2026-08-10",
      "buy_price": 73.8,
      "shares": 121.95122,
      "cost": 9000.0,
      "current_price": 73.06,
      "current_value": 8909.76,
      "pnl_pct": -1.0,
      "take_profit_pct": 0.5,
      "stop_loss_pct": -0.35,
      "status": "open",
      "exit": null,
      "sector": "Tech / AI Growth",
      "leverage": 3.0,
      "effective_value": 26729.28,
      "underlying": "QQQ",
      "underlying_stop_pct": -0.08,
      "underlying_buy_price": 720.87,
      "theory_ids": [
        "T1",
        "T7"
      ]
    },
    {
      "ticker": "SOXL",
      "name": "Direxion Daily Semiconductor Bull 3X Shares",
      "sleeve": "Tech/AI Growth",
      "buy_date": "2026-08-10",
      "buy_price": 130.0,
      "shares": 53.846154,
      "cost": 7000.0,
      "current_price": 133.0,
      "current_value": 7161.54,
      "pnl_pct": 2.31,
      "take_profit_pct": 0.6,
      "stop_loss_pct": -0.35,
      "status": "open",
      "exit": null,
      "sector": "Tech / AI Growth",
      "leverage": 3.0,
      "effective_value": 21484.62,
      "underlying": "SOXX",
      "underlying_stop_pct": -0.09,
      "underlying_buy_price": 529.39,
      "theory_ids": [
        "T1",
        "T7"
      ]
    },
    {
      "ticker": "NLR",
      "name": "VanEck Uranium and Nuclear ETF",
      "sleeve": "AI Power - Nuclear",
      "buy_date": "2026-08-10",
      "buy_price": 116.99,
      "shares": 59.834174,
      "cost": 7000.0,
      "current_price": 119.18,
      "current_value": 7131.04,
      "pnl_pct": 1.87,
      "take_profit_pct": 0.35,
      "stop_loss_pct": -0.18,
      "status": "open",
      "exit": null,
      "sector": "Nuclear / Power",
      "leverage": 1.0,
      "effective_value": 7131.04,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T3"
      ]
    },
    {
      "ticker": "ZROZ",
      "name": "PIMCO 25+ Year Zero Coupon U.S. Treasury ETF",
      "sleeve": "Crisis Alpha - AI Bust",
      "buy_date": "2026-08-10",
      "buy_price": 58.12,
      "shares": 103.235092,
      "cost": 6000.0,
      "current_price": 58.31,
      "current_value": 6019.64,
      "pnl_pct": 0.33,
      "take_profit_pct": 0.3,
      "stop_loss_pct": -0.15,
      "status": "open",
      "exit": null,
      "sector": "Hedge Stack",
      "leverage": 1.0,
      "effective_value": 6019.64,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T6"
      ]
    },
    {
      "ticker": "DBMF",
      "name": "iMGP DBi Managed Futures Strategy ETF",
      "sleeve": "Crisis Alpha - Trend",
      "buy_date": "2026-08-10",
      "buy_price": 31.32,
      "shares": 175.606641,
      "cost": 5500.0,
      "current_price": 31.33,
      "current_value": 5501.76,
      "pnl_pct": 0.03,
      "take_profit_pct": 0.2,
      "stop_loss_pct": -0.12,
      "status": "open",
      "exit": null,
      "sector": "Hedge Stack",
      "leverage": 1.0,
      "effective_value": 5501.76,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T6"
      ]
    },
    {
      "ticker": "BTAL",
      "name": "AGF U.S. Market Neutral Anti-Beta Fund",
      "sleeve": "Crisis Alpha - Anti-Beta",
      "buy_date": "2026-08-10",
      "buy_price": 12.08,
      "shares": 455.298013,
      "cost": 5500.0,
      "current_price": 11.91,
      "current_value": 5422.6,
      "pnl_pct": -1.41,
      "take_profit_pct": 0.15,
      "stop_loss_pct": -0.1,
      "status": "open",
      "exit": null,
      "sector": "Hedge Stack",
      "leverage": 1.0,
      "effective_value": 5422.6,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T6"
      ]
    },
    {
      "ticker": "DRAM",
      "name": "Roundhill Memory ETF (HBM / Memory)",
      "sleeve": "Tech/AI Growth",
      "buy_date": "2026-08-10",
      "buy_price": 49.6,
      "shares": 100.806452,
      "cost": 5000.0,
      "current_price": 50.89,
      "current_value": 5130.04,
      "pnl_pct": 2.6,
      "take_profit_pct": 0.5,
      "stop_loss_pct": -0.25,
      "status": "open",
      "exit": null,
      "sector": "Tech / AI Growth",
      "leverage": 1.0,
      "effective_value": 5130.04,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T2",
        "T1"
      ]
    },
    {
      "ticker": "SMH",
      "name": "VanEck Semiconductor ETF",
      "sleeve": "Tech/AI Growth",
      "buy_date": "2026-08-10",
      "buy_price": 569.41,
      "shares": 8.781016,
      "cost": 5000.0,
      "current_price": 572.93,
      "current_value": 5030.91,
      "pnl_pct": 0.62,
      "take_profit_pct": 0.4,
      "stop_loss_pct": -0.2,
      "status": "open",
      "exit": null,
      "sector": "Tech / AI Growth",
      "leverage": 1.0,
      "effective_value": 5030.91,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T1"
      ]
    },
    {
      "ticker": "NUKZ",
      "name": "Range Nuclear Renaissance ETF",
      "sleeve": "AI Power - Nuclear",
      "buy_date": "2026-08-10",
      "buy_price": 66.64,
      "shares": 60.02401,
      "cost": 4000.0,
      "current_price": 67.49,
      "current_value": 4051.02,
      "pnl_pct": 1.28,
      "take_profit_pct": 0.45,
      "stop_loss_pct": -0.25,
      "status": "open",
      "exit": null,
      "sector": "Nuclear / Power",
      "leverage": 1.0,
      "effective_value": 4051.02,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T3"
      ]
    },
    {
      "ticker": "FXY",
      "name": "Invesco CurrencyShares Japanese Yen Trust",
      "sleeve": "Crisis Alpha - Carry Unwind",
      "buy_date": "2026-08-10",
      "buy_price": 57.62,
      "shares": 69.42034,
      "cost": 4000.0,
      "current_price": 57.63,
      "current_value": 4000.69,
      "pnl_pct": 0.02,
      "take_profit_pct": 0.2,
      "stop_loss_pct": -0.12,
      "status": "open",
      "exit": null,
      "sector": "Hedge Stack",
      "leverage": 1.0,
      "effective_value": 4000.69,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T6"
      ]
    },
    {
      "ticker": "VIXM",
      "name": "ProShares VIX Mid-Term Futures ETF",
      "sleeve": "Crisis Alpha - Vol Decay",
      "buy_date": "2026-08-10",
      "buy_price": 14.28,
      "shares": 280.112045,
      "cost": 4000.0,
      "current_price": 14.24,
      "current_value": 3988.8,
      "pnl_pct": -0.28,
      "take_profit_pct": 0.4,
      "stop_loss_pct": -0.2,
      "status": "open",
      "exit": null,
      "sector": "Hedge Stack",
      "leverage": 1.0,
      "effective_value": 3988.8,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T6"
      ]
    },
    {
      "ticker": "QFLR",
      "name": "Innovator Nasdaq-100 Managed Floor ETF",
      "sleeve": "Crisis Alpha - Down-Day Floor",
      "buy_date": "2026-08-10",
      "buy_price": 35.49,
      "shares": 98.619327,
      "cost": 3500.0,
      "current_price": 35.43,
      "current_value": 3494.08,
      "pnl_pct": -0.17,
      "take_profit_pct": 0.2,
      "stop_loss_pct": -0.12,
      "status": "open",
      "exit": null,
      "sector": "Hedge Stack",
      "leverage": 1.0,
      "effective_value": 3494.08,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T6"
      ]
    },
    {
      "ticker": "GLD",
      "name": "SPDR Gold Shares",
      "sleeve": "Crisis Alpha - Real Assets",
      "buy_date": "2026-08-10",
      "buy_price": 402.54,
      "shares": 8.694794,
      "cost": 3500.0,
      "current_price": 400.96,
      "current_value": 3486.26,
      "pnl_pct": -0.39,
      "take_profit_pct": 0.2,
      "stop_loss_pct": -0.12,
      "status": "open",
      "exit": null,
      "sector": "Hedge Stack",
      "leverage": 1.0,
      "effective_value": 3486.26,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T9",
        "T6"
      ]
    },
    {
      "ticker": "GDX",
      "name": "VanEck Gold Miners ETF",
      "sleeve": "Crisis Alpha - Real Assets",
      "buy_date": "2026-08-10",
      "buy_price": 90.49,
      "shares": 38.678306,
      "cost": 3500.0,
      "current_price": 90.12,
      "current_value": 3485.69,
      "pnl_pct": -0.41,
      "take_profit_pct": 0.35,
      "stop_loss_pct": -0.2,
      "status": "open",
      "exit": null,
      "sector": "Hedge Stack",
      "leverage": 1.0,
      "effective_value": 3485.69,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T9",
        "T6"
      ]
    },
    {
      "ticker": "IWM",
      "name": "iShares Russell 2000 ETF",
      "sleeve": "Broadening / Value",
      "buy_date": "2026-08-10",
      "buy_price": 299.98,
      "shares": 10.000667,
      "cost": 3000.0,
      "current_price": 300.99,
      "current_value": 3010.1,
      "pnl_pct": 0.34,
      "take_profit_pct": 0.3,
      "stop_loss_pct": -0.15,
      "status": "open",
      "exit": null,
      "sector": "Broadening / Value",
      "leverage": 1.0,
      "effective_value": 3010.1,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T10"
      ]
    },
    {
      "ticker": "JEPQ",
      "name": "JPMorgan Nasdaq Equity Premium Income ETF",
      "sleeve": "Premium Financing",
      "buy_date": "2026-08-10",
      "buy_price": 59.68,
      "shares": 41.890081,
      "cost": 2500.0,
      "current_price": 59.65,
      "current_value": 2498.74,
      "pnl_pct": -0.05,
      "take_profit_pct": 0.2,
      "stop_loss_pct": -0.12,
      "status": "open",
      "exit": null,
      "sector": "Premium Financing",
      "leverage": 1.0,
      "effective_value": 2498.74,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T12"
      ]
    },
    {
      "ticker": "IWDL",
      "name": "ETRACS 2x Leveraged US Value Factor TR ETN",
      "sleeve": "Broadening / Value",
      "buy_date": "2026-08-10",
      "buy_price": 69.9752,
      "shares": 35.726519,
      "cost": 2500.0,
      "current_price": 69.8701,
      "current_value": 2496.22,
      "pnl_pct": -0.15,
      "take_profit_pct": 0.45,
      "stop_loss_pct": -0.35,
      "status": "open",
      "exit": null,
      "sector": "Broadening / Value",
      "leverage": 2.0,
      "effective_value": 4992.44,
      "underlying": "IWD",
      "underlying_stop_pct": -0.1,
      "underlying_buy_price": 258.31,
      "theory_ids": [
        "T15"
      ]
    },
    {
      "ticker": "XLY",
      "name": "Consumer Discretionary Select Sector SPDR Fund",
      "sleeve": "Contrarian Fear",
      "buy_date": "2026-08-10",
      "buy_price": 119.67,
      "shares": 20.890784,
      "cost": 2500.0,
      "current_price": 119.24,
      "current_value": 2491.02,
      "pnl_pct": -0.36,
      "take_profit_pct": 0.3,
      "stop_loss_pct": -0.15,
      "status": "open",
      "exit": null,
      "sector": "Contrarian Fear",
      "leverage": 1.0,
      "effective_value": 2491.02,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T13"
      ]
    },
    {
      "ticker": "EZU",
      "name": "iShares MSCI Eurozone ETF",
      "sleeve": "Contrarian Fear",
      "buy_date": "2026-08-10",
      "buy_price": 71.3,
      "shares": 28.05049,
      "cost": 2000.0,
      "current_price": 71.53,
      "current_value": 2006.45,
      "pnl_pct": 0.32,
      "take_profit_pct": 0.3,
      "stop_loss_pct": -0.15,
      "status": "open",
      "exit": null,
      "sector": "Contrarian Fear",
      "leverage": 1.0,
      "effective_value": 2006.45,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T13"
      ]
    },
    {
      "ticker": "PLTR",
      "name": "Palantir Technologies Inc.",
      "sleeve": "Tech/AI Growth",
      "buy_date": "2026-08-10",
      "buy_price": 175.23,
      "shares": 11.413455,
      "cost": 2000.0,
      "current_price": 174.94,
      "current_value": 1996.67,
      "pnl_pct": -0.17,
      "take_profit_pct": 0.4,
      "stop_loss_pct": -0.2,
      "status": "open",
      "exit": null,
      "sector": "Tech / AI Growth",
      "leverage": 1.0,
      "effective_value": 1996.67,
      "underlying": null,
      "underlying_stop_pct": null,
      "underlying_buy_price": null,
      "theory_ids": [
        "T14",
        "T1"
      ]
    }
  ],
  "sleeves": [
    {
      "sleeve": "Tech/AI Growth",
      "value": 28228.92
    },
    {
      "sleeve": "Short-Term Bonds (SGOV)",
      "value": 12975.65
    },
    {
      "sleeve": "AI Power - Nuclear",
      "value": 11182.06
    },
    {
      "sleeve": "Crisis Alpha - Real Assets",
      "value": 6971.95
    },
    {
      "sleeve": "Crisis Alpha - AI Bust",
      "value": 6019.64
    },
    {
      "sleeve": "Broadening / Value",
      "value": 5506.32
    },
    {
      "sleeve": "Crisis Alpha - Trend",
      "value": 5501.76
    },
    {
      "sleeve": "Crisis Alpha - Anti-Beta",
      "value": 5422.6
    },
    {
      "sleeve": "Contrarian Fear",
      "value": 4497.47
    },
    {
      "sleeve": "Crisis Alpha - Carry Unwind",
      "value": 4000.69
    },
    {
      "sleeve": "Crisis Alpha - Vol Decay",
      "value": 3988.8
    },
    {
      "sleeve": "Crisis Alpha - Down-Day Floor",
      "value": 3494.08
    },
    {
      "sleeve": "Premium Financing",
      "value": 2498.74
    }
  ],
  "sectors": [
    {
      "sector": "Tech / AI Growth",
      "value": 28228.92,
      "effective": 60371.52,
      "leverage": 2.14,
      "pct": 60.2,
      "max_pct": 70,
      "status": "ok",
      "note": "v5-expanded for 3x TQQQ/SOXL"
    },
    {
      "sector": "Nuclear / Power",
      "value": 11182.06,
      "effective": 11182.06,
      "leverage": 1.0,
      "pct": 11.1,
      "max_pct": 16,
      "status": "ok",
      "note": ""
    },
    {
      "sector": "Broadening / Value",
      "value": 5506.32,
      "effective": 8002.54,
      "leverage": 1.45,
      "pct": 8.0,
      "max_pct": 16,
      "status": "ok",
      "note": ""
    },
    {
      "sector": "Contrarian Fear",
      "value": 4497.47,
      "effective": 4497.47,
      "leverage": 1.0,
      "pct": 4.5,
      "max_pct": 12,
      "status": "ok",
      "note": ""
    },
    {
      "sector": "Hedge Stack",
      "value": 35399.52,
      "effective": 35399.52,
      "leverage": 1.0,
      "pct": 35.3,
      "max_pct": 45,
      "status": "ok",
      "note": ""
    },
    {
      "sector": "Premium Financing",
      "value": 2498.74,
      "effective": 2498.74,
      "leverage": 1.0,
      "pct": 2.5,
      "max_pct": 6,
      "status": "ok",
      "note": ""
    },
    {
      "sector": "Short-Term Bonds",
      "value": 12975.65,
      "effective": 12975.65,
      "leverage": 1.0,
      "pct": 12.9,
      "max_pct": 20,
      "status": "ok",
      "note": ""
    }
  ],
  "leverage_factor": 1.35,
  "history": [
    {
      "date": "2026-08-10",
      "total_value": 99999.97,
      "cash": 13000.0,
      "invested_value": 86999.97,
      "day_change": 500.0,
      "prices": {
        "TQQQ": 73.8,
        "SOXL": 130.0,
        "SMH": 569.41,
        "DRAM": 49.6,
        "PLTR": 175.23,
        "NLR": 116.99,
        "NUKZ": 66.64,
        "IWM": 299.98,
        "IWDL": 69.9752,
        "XLY": 119.67,
        "EZU": 71.3,
        "ZROZ": 58.12,
        "FXY": 57.62,
        "VIXM": 14.28,
        "QFLR": 35.49,
        "GLD": 402.54,
        "GDX": 90.49,
        "BTAL": 12.08,
        "DBMF": 31.32,
        "JEPQ": 59.68
      }
    },
    {
      "date": "2026-08-11",
      "total_value": 100313.66,
      "cash": 25.0,
      "invested_value": 100288.66,
      "day_change": 0.0,
      "prices": {
        "TQQQ": 73.06,
        "SOXL": 133.0,
        "SMH": 572.93,
        "DRAM": 50.89,
        "PLTR": 174.94,
        "NLR": 119.18,
        "NUKZ": 67.49,
        "IWM": 300.99,
        "IWDL": 69.8701,
        "XLY": 119.24,
        "EZU": 71.53,
        "ZROZ": 58.31,
        "FXY": 57.63,
        "VIXM": 14.24,
        "QFLR": 35.43,
        "GLD": 400.96,
        "GDX": 90.12,
        "BTAL": 11.91,
        "DBMF": 31.33,
        "JEPQ": 59.65,
        "SGOV": 100.51
      }
    }
  ],
  "events": [
    {
      "date": "2026-08-11",
      "ticker": "SGOV",
      "name": "iShares 0-3 Month Treasury Bond ETF",
      "reason": "deploy_cash",
      "price": 100.5,
      "buy_price": 100.5,
      "shares": 129.1045,
      "realized_pnl": 0
    },
    {
      "date": "2026-08-11",
      "ticker": "SGOV",
      "name": "iShares 0-3 Month Treasury Bond ETF",
      "reason": "deploy_cash",
      "price": 100.505,
      "buy_price": 100.505,
      "shares": 129.0981,
      "realized_pnl": 0
    }
  ],
  "theories": [
    {
      "id": "T1",
      "title": "AI infrastructure beats the S&P for the next 12 months",
      "prediction": "Combined semis sleeve (SOXL, SMH, DRAM) outperforms SPY by >20pp over the next 12 months.",
      "tier": "A",
      "tier_reason": "Well-documented $1T AI capex + semis >40% of Q2 EPS growth, but >20pp bar is high and semis are crowded.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: $1T global AI capex in 2026 (Goldman); semis >40% of Q2 EPS growth (UBS). Late-June selloff technical, not fundamental."
      ]
    },
    {
      "id": "T2",
      "title": "Memory (HBM) is the bottleneck - DRAM outperforms broad semis",
      "prediction": "DRAM ETF outperforms SMH over the next 6 months.",
      "tier": "B",
      "tier_reason": "Bottleneck is concrete (full bookings) but DRAM already ran hard - some mean-reversion risk.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: Micron capacity fully booked; DRAM +161.5% since Apr 2026, $23B AUM."
      ]
    },
    {
      "id": "T3",
      "title": "Nuclear/power is the next leg of the AI trade",
      "prediction": "NLR + NUKZ combined outperform SPY over the next 12 months.",
      "tier": "B",
      "tier_reason": "Structural (data centers, 20-yr PPAs) but a rotation bet with pullback risk.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: Data centers 6.7-12% of US electricity by 2028; hyperscalers signed 20-yr PPAs; uranium $88/lb +34% YoY."
      ]
    },
    {
      "id": "T6",
      "title": "Crisis-alpha stack cuts drawdown without killing upside",
      "prediction": "Portfolio max drawdown over the next 12 months stays under -35% while the hedge stack (ZROZ+FXY+VIXM+QFLR+GLD+GDX+BTAL+DBMF) contributes a combined net return greater than -5%.",
      "tier": "A",
      "tier_reason": "Purpose-built to cut drawdown; the >-5% net hedge return is the only uncertain leg.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: Hedges mapped to distinct crash mechanisms: deflation, carry-unwind, vol-spike, put-floor, real assets, anti-beta, trend."
      ]
    },
    {
      "id": "T7",
      "title": "Leverage pays in a persistent trend",
      "prediction": "SOXL + TQQQ combined beat a 1x equivalent (50% SMH + 50% QQQ) over the holding period because the AI trend persists and daily-decay losses are exceeded by trend gains.",
      "tier": "B",
      "tier_reason": "H1 2026 proof (SOXL +440%, TQQQ +43%) plus A-tier trend conviction; decay risk is the known cost. Re-rated C->B in v5.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: Leveraged products dominate when trends hard; decay is the offsetting risk."
      ]
    },
    {
      "id": "T8",
      "title": "Diversification beats raw tech concentration",
      "prediction": "The v5 book posts a materially shallower drawdown than the original v1 (12-position, 84% tech) book on the next -5% tech day, while still capturing at least 60% of the v1 upside over 12 months.",
      "tier": "S",
      "tier_reason": "Structural - cutting 84%->30% tech concentration MUST shallow drawdowns.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: Tech cut 84% -> 30%; crisis-alpha + cash enhance downside protection."
      ]
    },
    {
      "id": "T9",
      "title": "Gold hedges tech drawdowns",
      "prediction": "On days SPY falls >1%, GLD+GDX combined finish positive at least 40% of the time over the next 12 months.",
      "tier": "B",
      "tier_reason": "Historically common, not guaranteed - 40% bar is a fair, testable threshold.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: Gold resilient during Iran-war volatility; miners add downside-beta exposure tied to bullion."
      ]
    },
    {
      "id": "T10",
      "title": "Small-cap broadening outperforms SPY while AI consolidates",
      "prediction": "IWM outperforms SPY over the next 6 months as AI/hardware consolidates and breadth broadens.",
      "tier": "B",
      "tier_reason": "Equal-weight-vs-cap-weight divergence is verifiable breadth data; timing still not certain.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: S&P 500 equal-weight at highs while cap-weight slipped (July). XBI dropped from this bet in v5 (low catalyst)."
      ]
    },
    {
      "id": "T11",
      "title": "Hedge stack halves the loss on a crash week",
      "prediction": "On any week the Nasdaq falls >=10%, the hedge stack keeps the portfolio's total drawdown to less than half of what the identical book WITHOUT hedges would suffer.",
      "tier": "S",
      "tier_reason": "Close to structural: multiple uncorrelated crash instruments (rates, FX, vol, gold, anti-beta) fund the same event.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: Hedges mapped to distinct crash mechanisms."
      ]
    },
    {
      "id": "T12",
      "title": "Covered-call income adds book-level yield",
      "prediction": "JEPQ's cumulative distributions over 12 months are net-positive at the book level (distributions exceed JEPQ's own price/cap drag), i.e. the position pays to hold rather than costing the book.",
      "tier": "B",
      "tier_reason": "Rated down from the old 'premium financing' claim: JEPQ's ~0.25% book-level yield is far too small to fund the ~35% hedge stack. The hedges are priced insurance budgeted in T6 (net >-5% over 12mo), NOT financed by JEPQ. Honest testable claim: JEPQ itself is net-positive.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: JEPQ yield ~10% on a 2.5% position = ~0.25% book-level - small income sleeve, not a hedge-funding engine.",
        "2026-08-11 (v5.1): 'JEPQ funds the hedges' narrative deleted. Hedge drag is explicitly priced insurance (T6)."
      ]
    },
    {
      "id": "T13",
      "title": "Fear buys with catalysts beat SPY",
      "prediction": "XLY + EZU combined outperform SPY over the next 6 months, bought on the sentiment-vs-spending divergence and the Europe laggard+UBS-upgrade gap.",
      "tier": "B",
      "tier_reason": "Named catalysts (jobs improving; UBS upgrade; oil drop) lift conviction from C to B. KWEB excluded - fear without resolution.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: XLY = sour sentiment but resilient spending; EZU = laggard + UBS upgrade + cheaper valuations.",
        "2026-08-10 (v5): KWEB CUT - China regulatory/geopolitical risk unfundable at C conviction."
      ]
    },
    {
      "id": "T14",
      "title": "Selling the greed (PLTR trim) works",
      "prediction": "Keeping PLTR at just 2% (146x P/E, the greediest holding) reduces portfolio drawdown without costing more than 1pp of 12-month total return.",
      "tier": "B",
      "tier_reason": "Drawdown benefit likely; the <1pp opportunity-cost claim is the less certain half.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: 'Sell when others are greedy.' PLTR at 146x trailing P/E priced for perfection."
      ]
    },
    {
      "id": "T15",
      "title": "Value factor pays as rotation broadens",
      "prediction": "IWDL (2x value factor, held as anti-growth factor-hedge) outperforms the growth sleeve on a risk-adjusted (Sharpe) basis over the next 6 months.",
      "tier": "B",
      "tier_reason": "July's value-vs-growth divergence is evidence; re-rated C->B on breadth support. 2x decay = the cost.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10: Value beat growth by widest margin in 25 years (July, HB Wealth); equal-weight leadership should extend it."
      ]
    },
    {
      "id": "T16",
      "title": "Conviction discipline beats over-building",
      "prediction": "Cutting 4 low-conviction non-hedge positions (IGV, ARKQ, XBI, KWEB) and raising cash to 13% produces a lower max drawdown than v4 with no loss of up-capture over 12 months.",
      "tier": "B",
      "tier_reason": "Dropping darts and holding cash is almost always drawdown-friendly; up-capture is the testable half.",
      "status": "pending",
      "created": "2026-08-10",
      "last_updated": "2026-08-10",
      "evidence": [
        "2026-08-10 (v5): Cut IGV (D), ARKQ (C), XBI (C), KWEB (C) - all non-hedges. Cash 3.5% -> 13%. No C/D allowed unless it is a hedge."
      ]
    }
  ],
  "benchmark": {
    "label": "S&P 500 (SPY)",
    "start_value": 100000,
    "history": [
      {
        "date": "2026-08-10",
        "value": 100000.0
      },
      {
        "date": "2026-08-11",
        "value": 99680.48
      }
    ],
    "aligned": [
      {
        "date": "2026-08-10",
        "value": 100000.0
      },
      {
        "date": "2026-08-11",
        "value": 99680.48
      }
    ],
    "summary": {
      "total_return_pct": -0.32,
      "max_drawdown_pct": -0.32,
      "sharpe_annualized": null
    }
  },
  "rebalance": null,
  "news": {
    "asof": "2026-08-12 10:05:16",
    "big_stories": [
      {
        "title": "Software-as-a-Service (SaaS) Companies Are Making a Comeback. Here's the Exact SaaS Stock I Recommend Buying Right Now.",
        "link": "https://www.fool.com/investing/2026/08/12/software-as-a-service-saas-companies-are-making-a/?.tsrc=rss",
        "ts": 1786512000,
        "when": "Aug 12, 05:20 AM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "positive"
      },
      {
        "title": "JEPQ’s 10.9% Yield Hides $2,900 Annual Tax Bill Most Retirees Never See",
        "link": "https://247wallst.com/investing/etf/2026/08/11/jepqs-10-9-yield-hides-2900-annual-tax-bill-most-retirees-never-see/?.tsrc=rss",
        "ts": 1786485923,
        "when": "Aug 11, 10:05 PM",
        "ticker": "JEPQ",
        "industry": "Covered-Call Income",
        "theory": [
          "T12"
        ],
        "sent": "neutral"
      },
      {
        "title": "Sector Update: Consumer Stocks Decline Late Afternoon",
        "link": "https://finance.yahoo.com/markets/stocks/articles/sector-consumer-stocks-decline-afternoon-195018690.html?.tsrc=rss",
        "ts": 1786477818,
        "when": "Aug 11, 07:50 PM",
        "ticker": "XLY",
        "industry": "Consumer Disc.",
        "theory": [
          "T13"
        ],
        "sent": "neutral"
      },
      {
        "title": "If You Want More Upside From Gold, This ETF Offers a Different Kind of Leverage",
        "link": "https://www.barchart.com/story/news/3784926/if-you-want-more-upside-from-gold-this-etf-offers-a-different-kind-of-leverage?.tsrc=rss",
        "ts": 1786468495,
        "when": "Aug 11, 05:14 PM",
        "ticker": "GDX",
        "industry": "Gold Miners",
        "theory": [
          "T6",
          "T9",
          "T11"
        ],
        "sent": "positive"
      },
      {
        "title": "Trump's Polysilicon Tariffs Could Reshape These ETFs",
        "link": "https://finance.yahoo.com/economy/policy/articles/trumps-polysilicon-tariffs-could-reshape-135600837.html?.tsrc=rss",
        "ts": 1786456560,
        "when": "Aug 11, 01:56 PM",
        "ticker": "SMH",
        "industry": "Semis",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "negative"
      }
    ],
    "feed": [
      {
        "title": "Software-as-a-Service (SaaS) Companies Are Making a Comeback. Here's the Exact SaaS Stock I Recommend Buying Right Now.",
        "link": "https://www.fool.com/investing/2026/08/12/software-as-a-service-saas-companies-are-making-a/?.tsrc=rss",
        "ts": 1786512000,
        "when": "Aug 12, 05:20 AM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "positive"
      },
      {
        "title": "Cathie Wood Has Been Selling Palantir Into Every Rally Since Its 29% Earnings Pop",
        "link": "https://www.fool.com/investing/2026/08/11/cathie-wood-has-been-selling-palantir-into-every-r/?.tsrc=rss",
        "ts": 1786498020,
        "when": "Aug 12, 01:27 AM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "neutral"
      },
      {
        "title": "Michael Burry Adds To NVDA, PLTR, ORCL Shorts — Why He’s Thinking About 2005 Again",
        "link": "https://stocktwits.com/news-articles/markets/equity/michael-burry-adds-to-nvda-pltr-orcl-shorts-why-he-is-thinking-about-2005-again/cZoNOyZRJXV?.tsrc=rss",
        "ts": 1786488724,
        "when": "Aug 11, 10:52 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "neutral"
      },
      {
        "title": "JEPQ’s 10.9% Yield Hides $2,900 Annual Tax Bill Most Retirees Never See",
        "link": "https://247wallst.com/investing/etf/2026/08/11/jepqs-10-9-yield-hides-2900-annual-tax-bill-most-retirees-never-see/?.tsrc=rss",
        "ts": 1786485923,
        "when": "Aug 11, 10:05 PM",
        "ticker": "JEPQ",
        "industry": "Covered-Call Income",
        "theory": [
          "T12"
        ],
        "sent": "neutral"
      },
      {
        "title": "Your Father Retired With a Pension. You Got a 401(k) and a Brochure. These 4 ETFs Build the Pension Yourself",
        "link": "https://247wallst.com/investing/etf/2026/08/11/your-father-retired-with-a-pension-you-got-a-401k-and-a-brochure-these-4-etfs-build-the-pension-yourself/?.tsrc=rss",
        "ts": 1786485338,
        "when": "Aug 11, 09:55 PM",
        "ticker": "JEPQ",
        "industry": "Covered-Call Income",
        "theory": [
          "T12"
        ],
        "sent": "neutral"
      },
      {
        "title": "Palantir Technologies Inc. (PLTR) vs. Microsoft Corporation (MSFT): Can Palantir Pull Off a Microsoft-Style Comeback?",
        "link": "https://finance.yahoo.com/markets/stocks/articles/palantir-technologies-inc-pltr-vs-205832913.html?.tsrc=rss",
        "ts": 1786481912,
        "when": "Aug 11, 08:58 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "neutral"
      },
      {
        "title": "Palantir Technologies’s Q2 Earnings Call: Our Top 5 Analyst Questions",
        "link": "https://finance.yahoo.com/markets/stocks/articles/palantir-technologies-q2-earnings-call-204522159.html?.tsrc=rss",
        "ts": 1786481122,
        "when": "Aug 11, 08:45 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "positive"
      },
      {
        "title": "Prediction: Palantir Will Hit $220 This Year. There's 1 Clear Reason Why.",
        "link": "https://www.fool.com/investing/2026/08/11/prediction-palantir-will-hit-220-this-year-theres/?.tsrc=rss",
        "ts": 1786481040,
        "when": "Aug 11, 08:44 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "neutral"
      },
      {
        "title": "Sector Update: Consumer Stocks Decline Late Afternoon",
        "link": "https://finance.yahoo.com/markets/stocks/articles/sector-consumer-stocks-decline-afternoon-195018690.html?.tsrc=rss",
        "ts": 1786477818,
        "when": "Aug 11, 07:50 PM",
        "ticker": "XLY",
        "industry": "Consumer Disc.",
        "theory": [
          "T13"
        ],
        "sent": "neutral"
      },
      {
        "title": "Cathie Wood Is Dumping More Palantir Shares. But Revenue Growth and Swelling Cash Flows Bode Well for PLTR Stock.",
        "link": "https://www.barchart.com/story/news/3786468/cathie-wood-is-dumping-more-palantir-shares-but-revenue-growth-and-swelling-cash-flows-bode-well-for-pltr-stock?.tsrc=rss",
        "ts": 1786473843,
        "when": "Aug 11, 06:44 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "positive"
      },
      {
        "title": "Archer Aviation: Ready for Takeoff?",
        "link": "https://finance.yahoo.com/markets/stocks/articles/archer-aviation-ready-takeoff-184400772.html?.tsrc=rss",
        "ts": 1786473840,
        "when": "Aug 11, 06:44 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "neutral"
      },
      {
        "title": "Cathie Wood Just Sold $21 Million of Palantir Stock. Here's Why That Could Be a Big Mistake.",
        "link": "https://www.fool.com/investing/2026/08/11/cathie-wood-just-sold-21-million-of-palantir-stock/?.tsrc=rss",
        "ts": 1786471860,
        "when": "Aug 11, 06:11 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "neutral"
      },
      {
        "title": "Michael Burry Doubles Down Again Against Major AI Stock",
        "link": "https://finance.yahoo.com/markets/options/articles/michael-burry-doubles-down-again-174701348.html?.tsrc=rss",
        "ts": 1786470421,
        "when": "Aug 11, 05:47 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "neutral"
      },
      {
        "title": "Sector Update: Consumer Stocks Decline in Afternoon Trading",
        "link": "https://finance.yahoo.com/markets/stocks/articles/sector-consumer-stocks-decline-afternoon-174215170.html?.tsrc=rss",
        "ts": 1786470135,
        "when": "Aug 11, 05:42 PM",
        "ticker": "XLY",
        "industry": "Consumer Disc.",
        "theory": [
          "T13"
        ],
        "sent": "neutral"
      },
      {
        "title": "The Palantir Bull Case Is Getting Harder to Ignore",
        "link": "https://247wallst.com/investing/2026/08/11/the-palantir-bull-case-is-getting-harder-to-ignore/?.tsrc=rss",
        "ts": 1786469417,
        "when": "Aug 11, 05:30 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "neutral"
      },
      {
        "title": "If You Want More Upside From Gold, This ETF Offers a Different Kind of Leverage",
        "link": "https://www.barchart.com/story/news/3784926/if-you-want-more-upside-from-gold-this-etf-offers-a-different-kind-of-leverage?.tsrc=rss",
        "ts": 1786468495,
        "when": "Aug 11, 05:14 PM",
        "ticker": "GDX",
        "industry": "Gold Miners",
        "theory": [
          "T6",
          "T9",
          "T11"
        ],
        "sent": "positive"
      },
      {
        "title": "Palantir (PLTR) AI Drives US Targeting In Iran As Missile Bottleneck Emerges",
        "link": "https://finance.yahoo.com/technology/ai/articles/palantir-pltr-ai-drives-us-170931422.html?.tsrc=rss",
        "ts": 1786468171,
        "when": "Aug 11, 05:09 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "negative"
      },
      {
        "title": "Michael Burry Has a Stark Warning for Investors Betting on Today's Market",
        "link": "https://finance.yahoo.com/markets/stocks/articles/michael-burry-stark-warning-investors-155418654.html?.tsrc=rss",
        "ts": 1786463658,
        "when": "Aug 11, 03:54 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "negative"
      },
      {
        "title": "Down 0.5% in 2026, Is Palantir Stock a Buy?",
        "link": "https://www.fool.com/investing/2026/08/11/down-in-2026-is-palantir-stock-a-buy/?.tsrc=rss",
        "ts": 1786463400,
        "when": "Aug 11, 03:50 PM",
        "ticker": "PLTR",
        "industry": "AI Software",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "positive"
      },
      {
        "title": "Trump's Polysilicon Tariffs Could Reshape These ETFs",
        "link": "https://finance.yahoo.com/economy/policy/articles/trumps-polysilicon-tariffs-could-reshape-135600837.html?.tsrc=rss",
        "ts": 1786456560,
        "when": "Aug 11, 01:56 PM",
        "ticker": "SMH",
        "industry": "Semis",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "negative"
      },
      {
        "title": "Yum! Brands Stock: Is Wall Street Bullish or Bearish?",
        "link": "https://www.barchart.com/story/news/3777478/yum-brands-stock-is-wall-street-bullish-or-bearish?.tsrc=rss",
        "ts": 1786450855,
        "when": "Aug 11, 12:20 PM",
        "ticker": "XLY",
        "industry": "Consumer Disc.",
        "theory": [
          "T13"
        ],
        "sent": "positive"
      },
      {
        "title": "Best-Performing ETF Areas of Last Week",
        "link": "https://finance.yahoo.com/markets/stocks/articles/best-performing-etf-areas-last-120000689.html?.tsrc=rss",
        "ts": 1786449600,
        "when": "Aug 11, 12:00 PM",
        "ticker": "GLD",
        "industry": "Gold",
        "theory": [
          "T6",
          "T9",
          "T11"
        ],
        "sent": "positive"
      },
      {
        "title": "What Are Wall Street Analysts' Target Price for McDonald's Stock?",
        "link": "https://www.barchart.com/story/news/3776509/what-are-wall-street-analysts-target-price-for-mcdonald-s-stock?.tsrc=rss",
        "ts": 1786449572,
        "when": "Aug 11, 11:59 AM",
        "ticker": "XLY",
        "industry": "Consumer Disc.",
        "theory": [
          "T13"
        ],
        "sent": "neutral"
      },
      {
        "title": "Interest Rates, Oil Prices Limit Wall Street Pre-Bell; Asia Off, Europe Flat",
        "link": "https://finance.yahoo.com/markets/articles/interest-rates-oil-prices-limit-110752366.html?.tsrc=rss",
        "ts": 1786446472,
        "when": "Aug 11, 11:07 AM",
        "ticker": "SMH",
        "industry": "Semis",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "neutral"
      },
      {
        "title": "Where You Hold SCHD and JEPQ Matters More Than You Think: The Taxable vs. IRA Math",
        "link": "https://247wallst.com/personal-finance/2026/08/10/where-you-hold-schd-and-jepq-matters-more-than-you-think-the-taxable-vs-ira-math/?.tsrc=rss",
        "ts": 1786399693,
        "when": "Aug 10, 10:08 PM",
        "ticker": "JEPQ",
        "industry": "Covered-Call Income",
        "theory": [
          "T12"
        ],
        "sent": "neutral"
      },
      {
        "title": "Semiconductor ETFs See Profit-Taking as Investors Pile Into QQQ",
        "link": "http://www.etf.com/sections/weekly-etf-flows/semiconductor-etfs-see-profit-taking-investors-pile-qqq?utm_source=yahoo-finance&utm_medium=rss&utm_campaign=yahoo-finance-rss&.tsrc=rss",
        "ts": 1786396615,
        "when": "Aug 10, 09:16 PM",
        "ticker": "SMH",
        "industry": "Semis",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "positive"
      },
      {
        "title": "ETF League Tables: Roundhill Gains $315M",
        "link": "http://www.etf.com/sections/etf-league-tables/etf-league-tables-roundhill-gains-315m?utm_source=yahoo-finance&utm_medium=rss&utm_campaign=yahoo-finance-rss&.tsrc=rss",
        "ts": 1786395730,
        "when": "Aug 10, 09:02 PM",
        "ticker": "DRAM",
        "industry": "AI Memory/HBM",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "positive"
      },
      {
        "title": "Is Now the Time to Invest in Bonds?",
        "link": "https://finance.yahoo.com/markets/options/articles/now-time-invest-bonds-201600575.html?.tsrc=rss",
        "ts": 1786392960,
        "when": "Aug 10, 08:16 PM",
        "ticker": "SGOV",
        "industry": "Equities",
        "theory": [],
        "sent": "neutral"
      },
      {
        "title": "The ETFs Most Exposed to the 2026 Chip Supply Chain Crisis — Winners and Losers",
        "link": "http://www.etf.com/sections/news/etfs-most-exposed-2026-chip-supply-chain-crisis-winners-and-losers?utm_source=yahoo-finance&utm_medium=rss&utm_campaign=yahoo-finance-rss&.tsrc=rss",
        "ts": 1786392922,
        "when": "Aug 10, 08:15 PM",
        "ticker": "SMH",
        "industry": "Semis",
        "theory": [
          "T1",
          "T7",
          "T2",
          "T14"
        ],
        "sent": "neutral"
      },
      {
        "title": "Sector Update: Consumer Stocks Lower in Late Afternoon Trading",
        "link": "https://finance.yahoo.com/markets/stocks/articles/sector-consumer-stocks-lower-afternoon-195537186.html?.tsrc=rss",
        "ts": 1786391737,
        "when": "Aug 10, 07:55 PM",
        "ticker": "XLY",
        "industry": "Consumer Disc.",
        "theory": [
          "T13"
        ],
        "sent": "negative"
      }
    ]
  }
};
