/* AUTO-GENERATED by leaderboards.py from portfolio.json / community/ - do not edit by hand. */
window.LEADERBOARDS = {
  "asof": "2026-08-25 19:25:18",
  "top_n": 10,
  "strategy_count": 8,
  "windows": {
    "weekly": {
      "label": "Last 5 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 0.16,
          "max_drawdown_pct": -3.16,
          "sharpe": 0.41
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": 0.12,
          "max_drawdown_pct": -1.66,
          "sharpe": 0.43
        },
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -0.31,
          "max_drawdown_pct": -0.84,
          "sharpe": -1.94
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -0.47,
          "max_drawdown_pct": -0.57,
          "sharpe": -7.82
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -1.13,
          "max_drawdown_pct": -1.56,
          "sharpe": -5.67
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.5,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.59
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.5,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.59
        },
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -3.65,
          "max_drawdown_pct": -4.85,
          "sharpe": -6.1
        }
      ]
    },
    "monthly": {
      "label": "Last 21 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 10.22,
          "max_drawdown_pct": -10.55,
          "sharpe": 2.08
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 5.82,
          "max_drawdown_pct": -6.7,
          "sharpe": 1.7
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 3.99,
          "max_drawdown_pct": -3.52,
          "sharpe": 2.22
        },
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 3.51,
          "max_drawdown_pct": -1.96,
          "sharpe": 3.26
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -0.47,
          "max_drawdown_pct": -0.57,
          "sharpe": -7.82
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -0.66,
          "max_drawdown_pct": -4.64,
          "sharpe": -0.56
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -2.81,
          "max_drawdown_pct": -3.62,
          "sharpe": -4.55
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.5,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.59
        }
      ]
    },
    "quarterly": {
      "label": "Last 63 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 2.19,
          "max_drawdown_pct": -4.49,
          "sharpe": 0.7
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -0.47,
          "max_drawdown_pct": -0.57,
          "sharpe": -7.82
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -0.66,
          "max_drawdown_pct": -4.64,
          "sharpe": -0.56
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -2.76,
          "max_drawdown_pct": -11.22,
          "sharpe": -0.31
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -2.81,
          "max_drawdown_pct": -3.62,
          "sharpe": -4.55
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.5,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.59
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -10.03,
          "max_drawdown_pct": -24.47,
          "sharpe": -0.62
        },
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -14.53,
          "max_drawdown_pct": -33.64,
          "sharpe": -0.46
        }
      ]
    },
    "yearly": {
      "label": "Last 252 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 55.64,
          "max_drawdown_pct": -36.97,
          "sharpe": 1.05
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 27.36,
          "max_drawdown_pct": -28.38,
          "sharpe": 0.82
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 24.62,
          "max_drawdown_pct": -11.96,
          "sharpe": 1.22
        },
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 19.87,
          "max_drawdown_pct": -8.88,
          "sharpe": 1.48
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -0.47,
          "max_drawdown_pct": -0.57,
          "sharpe": -7.82
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -0.66,
          "max_drawdown_pct": -4.64,
          "sharpe": -0.56
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -2.81,
          "max_drawdown_pct": -3.62,
          "sharpe": -4.55
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.5,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.59
        }
      ]
    },
    "all_time": {
      "label": "Since project inception (same window for all — fair compare)",
      "rows": [
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -0.51,
          "max_drawdown_pct": -0.57,
          "sharpe": -7.82
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -0.66,
          "max_drawdown_pct": -4.64,
          "sharpe": -0.56
        },
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -1.03,
          "max_drawdown_pct": -18.76,
          "sharpe": 1.09
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -1.49,
          "max_drawdown_pct": -41.87,
          "sharpe": 0.59
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -1.6,
          "max_drawdown_pct": -22.77,
          "sharpe": 1.05
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -2.81,
          "max_drawdown_pct": -3.62,
          "sharpe": -4.55
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -4.17,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.59
        },
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -5.31,
          "max_drawdown_pct": -58.04,
          "sharpe": 0.89
        }
      ]
    }
  }
};
