/* AUTO-GENERATED by leaderboards.py from portfolio.json / community/ - do not edit by hand. */
window.LEADERBOARDS = {
  "asof": "2026-08-26 02:24:31",
  "top_n": 10,
  "strategy_count": 8,
  "windows": {
    "weekly": {
      "label": "Last 5 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 0.66,
          "max_drawdown_pct": -3.16,
          "sharpe": 1.24
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": 0.28,
          "max_drawdown_pct": -1.66,
          "sharpe": 0.86
        },
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -0.2,
          "max_drawdown_pct": -0.84,
          "sharpe": -1.18
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -0.28,
          "max_drawdown_pct": -0.38,
          "sharpe": -6.5
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -0.95,
          "max_drawdown_pct": -1.56,
          "sharpe": -4.35
        },
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -3.12,
          "max_drawdown_pct": -4.85,
          "sharpe": -4.75
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.32,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.21
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.32,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.21
        }
      ]
    },
    "monthly": {
      "label": "Last 21 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 10.84,
          "max_drawdown_pct": -10.55,
          "sharpe": 2.18
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 6.35,
          "max_drawdown_pct": -6.7,
          "sharpe": 1.83
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 4.19,
          "max_drawdown_pct": -3.52,
          "sharpe": 2.32
        },
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 3.63,
          "max_drawdown_pct": -1.96,
          "sharpe": 3.37
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -0.28,
          "max_drawdown_pct": -0.38,
          "sharpe": -6.5
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -0.51,
          "max_drawdown_pct": -4.64,
          "sharpe": -0.4
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -2.62,
          "max_drawdown_pct": -3.62,
          "sharpe": -4.24
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.32,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.21
        }
      ]
    },
    "quarterly": {
      "label": "Last 63 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 2.3,
          "max_drawdown_pct": -4.49,
          "sharpe": 0.73
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -0.28,
          "max_drawdown_pct": -0.38,
          "sharpe": -6.5
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -0.51,
          "max_drawdown_pct": -4.64,
          "sharpe": -0.4
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -2.57,
          "max_drawdown_pct": -11.22,
          "sharpe": -0.28
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -2.62,
          "max_drawdown_pct": -3.62,
          "sharpe": -4.24
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.32,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.21
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -9.58,
          "max_drawdown_pct": -24.47,
          "sharpe": -0.57
        },
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -14.06,
          "max_drawdown_pct": -33.64,
          "sharpe": -0.43
        }
      ]
    },
    "yearly": {
      "label": "Last 252 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 56.51,
          "max_drawdown_pct": -36.97,
          "sharpe": 1.06
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 27.99,
          "max_drawdown_pct": -28.38,
          "sharpe": 0.83
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 24.86,
          "max_drawdown_pct": -11.96,
          "sharpe": 1.23
        },
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 20.0,
          "max_drawdown_pct": -8.88,
          "sharpe": 1.49
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -0.28,
          "max_drawdown_pct": -0.38,
          "sharpe": -6.5
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -0.51,
          "max_drawdown_pct": -4.64,
          "sharpe": -0.4
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -2.62,
          "max_drawdown_pct": -3.62,
          "sharpe": -4.24
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.32,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.21
        }
      ]
    },
    "all_time": {
      "label": "Since project inception (same window for all — fair compare)",
      "rows": [
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -0.32,
          "max_drawdown_pct": -0.38,
          "sharpe": -6.5
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -0.51,
          "max_drawdown_pct": -4.64,
          "sharpe": -0.4
        },
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -0.92,
          "max_drawdown_pct": -18.76,
          "sharpe": 1.1
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -1.0,
          "max_drawdown_pct": -41.87,
          "sharpe": 0.59
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -1.41,
          "max_drawdown_pct": -22.77,
          "sharpe": 1.06
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -2.62,
          "max_drawdown_pct": -3.62,
          "sharpe": -4.24
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.98,
          "max_drawdown_pct": -3.62,
          "sharpe": -6.21
        },
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -4.78,
          "max_drawdown_pct": -58.04,
          "sharpe": 0.89
        }
      ]
    }
  }
};
