/* AUTO-GENERATED by leaderboards.py from portfolio.json / community/ - do not edit by hand. */
window.LEADERBOARDS = {
  "asof": "2026-09-03 16:57:06",
  "top_n": 10,
  "strategy_count": 8,
  "windows": {
    "weekly": {
      "label": "Last 5 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 0.22,
          "max_drawdown_pct": -1.21,
          "sharpe": 1.07
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -0.5,
          "max_drawdown_pct": -1.87,
          "sharpe": -1.67
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -0.97,
          "max_drawdown_pct": -2.61,
          "sharpe": -2.73
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -1.28,
          "max_drawdown_pct": -1.38,
          "sharpe": -9.69
        },
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -1.76,
          "max_drawdown_pct": -5.66,
          "sharpe": -1.86
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -1.8,
          "max_drawdown_pct": -4.77,
          "sharpe": -2.65
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -4.29,
          "max_drawdown_pct": -4.29,
          "sharpe": -8.01
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -4.29,
          "max_drawdown_pct": -4.29,
          "sharpe": -8.01
        }
      ]
    },
    "monthly": {
      "label": "Last 21 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 0.39,
          "max_drawdown_pct": -2.07,
          "sharpe": 0.62
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 0.03,
          "max_drawdown_pct": -3.52,
          "sharpe": 0.09
        },
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -1.14,
          "max_drawdown_pct": -10.55,
          "sharpe": -0.16
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -1.28,
          "max_drawdown_pct": -1.38,
          "sharpe": -9.69
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -1.42,
          "max_drawdown_pct": -7.04,
          "sharpe": -0.47
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -1.48,
          "max_drawdown_pct": -5.86,
          "sharpe": -1.01
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.6,
          "max_drawdown_pct": -4.29,
          "sharpe": -5.72
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -4.29,
          "max_drawdown_pct": -4.29,
          "sharpe": -8.01
        }
      ]
    },
    "quarterly": {
      "label": "Last 63 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 2.33,
          "max_drawdown_pct": -4.18,
          "sharpe": 0.74
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -1.28,
          "max_drawdown_pct": -1.38,
          "sharpe": -9.69
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -1.48,
          "max_drawdown_pct": -5.86,
          "sharpe": -1.01
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -3.01,
          "max_drawdown_pct": -10.96,
          "sharpe": -0.35
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.6,
          "max_drawdown_pct": -4.29,
          "sharpe": -5.72
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -4.29,
          "max_drawdown_pct": -4.29,
          "sharpe": -8.01
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -12.31,
          "max_drawdown_pct": -23.56,
          "sharpe": -0.81
        },
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -15.31,
          "max_drawdown_pct": -32.08,
          "sharpe": -0.49
        }
      ]
    },
    "yearly": {
      "label": "Last 252 trading sessions",
      "rows": [
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 62.67,
          "max_drawdown_pct": -36.97,
          "sharpe": 1.13
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 29.86,
          "max_drawdown_pct": -28.38,
          "sharpe": 0.87
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 26.47,
          "max_drawdown_pct": -11.96,
          "sharpe": 1.3
        },
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": 21.37,
          "max_drawdown_pct": -8.88,
          "sharpe": 1.58
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -1.28,
          "max_drawdown_pct": -1.38,
          "sharpe": -9.69
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -1.48,
          "max_drawdown_pct": -5.86,
          "sharpe": -1.01
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.6,
          "max_drawdown_pct": -4.29,
          "sharpe": -5.72
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -4.29,
          "max_drawdown_pct": -4.29,
          "sharpe": -8.01
        }
      ]
    },
    "all_time": {
      "label": "Since project inception (same window for all — fair compare)",
      "rows": [
        {
          "strategy_id": "benchmark-spy",
          "name": "SPY",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -0.03,
          "max_drawdown_pct": -18.76,
          "sharpe": 1.17
        },
        {
          "strategy_id": "benchmark-qqq",
          "name": "QQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -0.47,
          "max_drawdown_pct": -22.77,
          "sharpe": 1.15
        },
        {
          "strategy_id": "benchmark-tqqq60-tmf40",
          "name": "TQQQ60/TMF40",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -0.77,
          "max_drawdown_pct": -41.87,
          "sharpe": 0.66
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-21",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-21",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -1.32,
          "max_drawdown_pct": -1.38,
          "sharpe": -9.69
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First",
          "author": "RubySapior",
          "kind": null,
          "return_pct": -1.48,
          "max_drawdown_pct": -5.86,
          "sharpe": -1.01
        },
        {
          "strategy_id": "benchmark-tqqq",
          "name": "TQQQ",
          "author": "Benchmark",
          "kind": "benchmark",
          "return_pct": -2.43,
          "max_drawdown_pct": -58.04,
          "sharpe": 0.98
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-16",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-16",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -3.6,
          "max_drawdown_pct": -4.29,
          "sharpe": -5.72
        },
        {
          "strategy_id": "hypergrowth-sharpe-barbell-v2026-08-17",
          "name": "HyperGrowth Sharpe Barbell v5 - Conviction-First 2026-08-17",
          "author": "Snapshot",
          "kind": "snapshot",
          "return_pct": -4.95,
          "max_drawdown_pct": -4.29,
          "sharpe": -8.01
        }
      ]
    }
  }
};
